### ISSUE TITLE
enhancement : add a final GCODE sequence after all prints are done

### ISSUE THREAD

**Issue by jlirochon** [nukeem/continuousprint#11]
could be used to cool down, disable steppers, play sounds...

context : I use the plugin with GCODE that ejects printed parts out of the bed after each print (I am batching covid19 shields). Works great so far, but as I don't cool down nor disable steppers between prints, I miss this functionality at the end of the queue.

**Comment by nukeem** [comment]
I'll take a look into it.

**Comment by nukeem** [comment]
Added new setting in latest version 1.0.3
