### ISSUE TITLE
Folders are not read

### ISSUE THREAD

**Issue by gestadieu** [nukeem/continuousprint#3]
Hi, 
thanks for the plugin, I want to try it for some projects but I already notice that I can't add files in the queue if they are inside a folder, is it a bug or am I missing something?
I was also thinking that maybe adding an icon to add to the queue from the Octoprint list of files/folders could be easier? The icon could be next to those already existing: Download, Remove, Load, Load and Print. 
What do you think?

**Comment by nukeem** [comment]
Thanks for the suggestion, that was actually what i attempted in the first place but found it difficult to get the button to work correctly.
As far as i'm aware the files should include folders but i don't tend to use folders so didn't test this. I'll take a look

**Comment by nukeem** [comment]
You were correct that folders were not being shown, i have updated to include all gcode files with a search for easier finding.
