### ISSUE TITLE
Updating to 1.0.1 Fails

### ISSUE THREAD

**Issue by SrgntBallistic** [nukeem/continuousprint#9]
Received a prompt to update the plugin to 1.0.1 this morning. I click "Update now" and the installations begins.

![image](https://user-images.githubusercontent.com/25190883/80381592-257e4100-886f-11ea-8f0a-645af95b108a.png)

At the end of the installation I notice it says it successfully install 1.0.0. I check the plugin in the manager and it indeed says it's still on 1.0.0

![image](https://user-images.githubusercontent.com/25190883/80381475-fa93ed00-886e-11ea-8f90-21b8e15121a3.png)

**Comment by taker218** [comment]
Had the same issue.
Just had a look at the setup.py and the plugin_version is still 1.0.0 so I guess you have the newest version, but @nukeem needs to change the version in the setup.py so you don't run into this update loop :)

**Comment by ViPeR5000** [comment]
Same here.
Upgrade loop :D

**Comment by fabien78** [comment]
It is the same for me.

**Comment by nukeem** [comment]
Thanks for letting me know, annoyingly the change didn't push and i didn't notice. Should be ok now.

**Comment by fabien78** [comment]
Unfortunatly not.
It is the same issue.
I saw a little thing which, maybe, will help you to understand the problem. At the end of the updating message, it is written:
"successfully installed continuousprint -1.0.0"

I hope you understand me well besouse my english is a little poor....

**Comment by taker218** [comment]
Seems like you need to add a new release, or else octoprint will always download the master.zip from the faulty 1.0.1

Maybe just change the version number to 1.0.2 and add a new release, that way it should download the new relase.

**Comment by nukeem** [comment]
Sorry everyone this is my first octoprint plugin. Just done a new 1.0.2 release now.

**Comment by ViPeR5000** [comment]
same loop again :/

**Comment by nukeem** [comment]
I've deleted the previous release, though octoprint is still trying to download it for some reason. I'm wondering if there is a delay before octoprint notices the new release

**Comment by nukeem** [comment]
Its worked for me now, required an octoprint restart

**Comment by taker218** [comment]
you need to force the update cache to be renewed.
Under settings -> Software update -> Advanced (or whatever it is in english) and then force update

With this it worked for me too. No update loop here on both my instances.

**Comment by fabien78** [comment]
Normal process for update is good now.

I don't see differences betwen the old version (but maybe nothing visible for the user)

**Comment by nukeem** [comment]
Nothing visiable except a search bar on files list

**Comment by SrgntBallistic** [comment]
I was able to use the force update on one of my Pi's to get it to update to 1.0.2. On another I couldn't get it to work with the exact same steps and numerous tries.

I ended up having to uninstall and reinstall the plugin. Obviously backup your gcode first if you have to take these steps. I did the full uninstall where it deletes all plugin data.

I have 2 more Pi's/Printers running prints. I'll see how well they update after they finish.
